# Generated by Django 4.2.11 on 2024-05-21 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0002_propiedad_propietario_alter_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='propietario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='static_pages.usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
