# Generated by Django 4.2.11 on 2024-05-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0004_comuna_inmueble_region_tipoinmueble_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comuna',
            options={'ordering': ['nombre'], 'verbose_name': 'Comuna', 'verbose_name_plural': 'Comunas'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['nombre'], 'verbose_name': 'Region', 'verbose_name_plural': 'Regiones'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['nombres'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='propiedad',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='propiedades_imagenes/'),
        ),
        migrations.DeleteModel(
            name='Inmueble',
        ),
        migrations.DeleteModel(
            name='TipoInmueble',
        ),
    ]
