# Generated by Django 4.2.11 on 2024-05-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0005_alter_comuna_options_alter_region_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img_propiedades/'),
        ),
    ]
