# Generated by Django 4.2.11 on 2024-05-22 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0007_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
