# Generated by Django 4.2.11 on 2024-05-23 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('static_pages', '0008_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='static_pages.comuna'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='propietario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
